/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppUsersRouteImport } from './routes/app.users'
import { Route as AppTrainingRouteImport } from './routes/app.training'
import { Route as AppTenantsRouteImport } from './routes/app.tenants'
import { Route as AppTeacherClassesRouteImport } from './routes/app.teacher-classes'
import { Route as AppSwimReportsRouteImport } from './routes/app.swim-reports'
import { Route as AppStudentsRouteImport } from './routes/app.students'
import { Route as AppSrbRouteImport } from './routes/app.srb'
import { Route as AppSquadRouteImport } from './routes/app.squad'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppMigrationRouteImport } from './routes/app.migration'
import { Route as AppMessagesRouteImport } from './routes/app.messages'
import { Route as AppMarketplaceRouteImport } from './routes/app.marketplace'
import { Route as AppMarketingRouteImport } from './routes/app.marketing'
import { Route as AppLmsRouteImport } from './routes/app.lms'
import { Route as AppGradingRouteImport } from './routes/app.grading'
import { Route as AppGradesRouteImport } from './routes/app.grades'
import { Route as AppFinanceRouteImport } from './routes/app.finance'
import { Route as AppCoursesRouteImport } from './routes/app.courses'
import { Route as AppComplianceRouteImport } from './routes/app.compliance'
import { Route as AppCoachingRouteImport } from './routes/app.coaching'
import { Route as AppChildrenRouteImport } from './routes/app.children'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppBrandingRouteImport } from './routes/app.branding'
import { Route as AppAwardsRouteImport } from './routes/app.awards'
import { Route as AppAttendanceRouteImport } from './routes/app.attendance'
import { Route as AppAssignmentsRouteImport } from './routes/app.assignments'
import { Route as AppAppraisalsRouteImport } from './routes/app.appraisals'
import { Route as AppAiInsightsRouteImport } from './routes/app.ai-insights'
import { Route as AppTrainingIndexRouteImport } from './routes/app.training.index'
import { Route as AppSrbIndexRouteImport } from './routes/app.srb.index'
import { Route as AppCoursesIndexRouteImport } from './routes/app.courses.index'
import { Route as AppAttendanceIndexRouteImport } from './routes/app.attendance.index'
import { Route as AppAppraisalsIndexRouteImport } from './routes/app.appraisals.index'
import { Route as AppTrainingCourseIdRouteImport } from './routes/app.training.$courseId'
import { Route as AppSrbStudentIdRouteImport } from './routes/app.srb.$studentId'
import { Route as AppSessionsSessionIdRouteImport } from './routes/app.sessions.$sessionId'
import { Route as AppInvoiceIdRouteImport } from './routes/app.invoice.$id'
import { Route as AppCoursesCourseIdRouteImport } from './routes/app.courses.$courseId'
import { Route as AppCertificateProgressIdRouteImport } from './routes/app.certificate.$progressId'
import { Route as AppAttendanceTakeRouteImport } from './routes/app.attendance.take'
import { Route as AppAppraisalsTeacherIdRouteImport } from './routes/app.appraisals.$teacherId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTrainingRoute = AppTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AppRoute,
} as any)
const AppTenantsRoute = AppTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherClassesRoute = AppTeacherClassesRouteImport.update({
  id: '/teacher-classes',
  path: '/teacher-classes',
  getParentRoute: () => AppRoute,
} as any)
const AppSwimReportsRoute = AppSwimReportsRouteImport.update({
  id: '/swim-reports',
  path: '/swim-reports',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppSrbRoute = AppSrbRouteImport.update({
  id: '/srb',
  path: '/srb',
  getParentRoute: () => AppRoute,
} as any)
const AppSquadRoute = AppSquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppMigrationRoute = AppMigrationRouteImport.update({
  id: '/migration',
  path: '/migration',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingRoute = AppMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AppRoute,
} as any)
const AppLmsRoute = AppLmsRouteImport.update({
  id: '/lms',
  path: '/lms',
  getParentRoute: () => AppRoute,
} as any)
const AppGradingRoute = AppGradingRouteImport.update({
  id: '/grading',
  path: '/grading',
  getParentRoute: () => AppRoute,
} as any)
const AppGradesRoute = AppGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesRoute = AppCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceRoute = AppComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachingRoute = AppCoachingRouteImport.update({
  id: '/coaching',
  path: '/coaching',
  getParentRoute: () => AppRoute,
} as any)
const AppChildrenRoute = AppChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandingRoute = AppBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => AppRoute,
} as any)
const AppAwardsRoute = AppAwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAssignmentsRoute = AppAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => AppRoute,
} as any)
const AppAppraisalsRoute = AppAppraisalsRouteImport.update({
  id: '/appraisals',
  path: '/appraisals',
  getParentRoute: () => AppRoute,
} as any)
const AppAiInsightsRoute = AppAiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => AppRoute,
} as any)
const AppTrainingIndexRoute = AppTrainingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTrainingRoute,
} as any)
const AppSrbIndexRoute = AppSrbIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSrbRoute,
} as any)
const AppCoursesIndexRoute = AppCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCoursesRoute,
} as any)
const AppAttendanceIndexRoute = AppAttendanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAttendanceRoute,
} as any)
const AppAppraisalsIndexRoute = AppAppraisalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAppraisalsRoute,
} as any)
const AppTrainingCourseIdRoute = AppTrainingCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => AppTrainingRoute,
} as any)
const AppSrbStudentIdRoute = AppSrbStudentIdRouteImport.update({
  id: '/$studentId',
  path: '/$studentId',
  getParentRoute: () => AppSrbRoute,
} as any)
const AppSessionsSessionIdRoute = AppSessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoiceIdRoute = AppInvoiceIdRouteImport.update({
  id: '/invoice/$id',
  path: '/invoice/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesCourseIdRoute = AppCoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => AppCoursesRoute,
} as any)
const AppCertificateProgressIdRoute =
  AppCertificateProgressIdRouteImport.update({
    id: '/certificate/$progressId',
    path: '/certificate/$progressId',
    getParentRoute: () => AppRoute,
  } as any)
const AppAttendanceTakeRoute = AppAttendanceTakeRouteImport.update({
  id: '/take',
  path: '/take',
  getParentRoute: () => AppAttendanceRoute,
} as any)
const AppAppraisalsTeacherIdRoute = AppAppraisalsTeacherIdRouteImport.update({
  id: '/$teacherId',
  path: '/$teacherId',
  getParentRoute: () => AppAppraisalsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/ai-insights': typeof AppAiInsightsRoute
  '/app/appraisals': typeof AppAppraisalsRouteWithChildren
  '/app/assignments': typeof AppAssignmentsRoute
  '/app/attendance': typeof AppAttendanceRouteWithChildren
  '/app/awards': typeof AppAwardsRoute
  '/app/branding': typeof AppBrandingRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/children': typeof AppChildrenRoute
  '/app/coaching': typeof AppCoachingRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/courses': typeof AppCoursesRouteWithChildren
  '/app/finance': typeof AppFinanceRoute
  '/app/grades': typeof AppGradesRoute
  '/app/grading': typeof AppGradingRoute
  '/app/lms': typeof AppLmsRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/migration': typeof AppMigrationRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/squad': typeof AppSquadRoute
  '/app/srb': typeof AppSrbRouteWithChildren
  '/app/students': typeof AppStudentsRoute
  '/app/swim-reports': typeof AppSwimReportsRoute
  '/app/teacher-classes': typeof AppTeacherClassesRoute
  '/app/tenants': typeof AppTenantsRoute
  '/app/training': typeof AppTrainingRouteWithChildren
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
  '/app/appraisals/$teacherId': typeof AppAppraisalsTeacherIdRoute
  '/app/attendance/take': typeof AppAttendanceTakeRoute
  '/app/certificate/$progressId': typeof AppCertificateProgressIdRoute
  '/app/courses/$courseId': typeof AppCoursesCourseIdRoute
  '/app/invoice/$id': typeof AppInvoiceIdRoute
  '/app/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/app/srb/$studentId': typeof AppSrbStudentIdRoute
  '/app/training/$courseId': typeof AppTrainingCourseIdRoute
  '/app/appraisals/': typeof AppAppraisalsIndexRoute
  '/app/attendance/': typeof AppAttendanceIndexRoute
  '/app/courses/': typeof AppCoursesIndexRoute
  '/app/srb/': typeof AppSrbIndexRoute
  '/app/training/': typeof AppTrainingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/ai-insights': typeof AppAiInsightsRoute
  '/app/assignments': typeof AppAssignmentsRoute
  '/app/awards': typeof AppAwardsRoute
  '/app/branding': typeof AppBrandingRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/children': typeof AppChildrenRoute
  '/app/coaching': typeof AppCoachingRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/finance': typeof AppFinanceRoute
  '/app/grades': typeof AppGradesRoute
  '/app/grading': typeof AppGradingRoute
  '/app/lms': typeof AppLmsRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/migration': typeof AppMigrationRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/squad': typeof AppSquadRoute
  '/app/students': typeof AppStudentsRoute
  '/app/swim-reports': typeof AppSwimReportsRoute
  '/app/teacher-classes': typeof AppTeacherClassesRoute
  '/app/tenants': typeof AppTenantsRoute
  '/app/users': typeof AppUsersRoute
  '/app': typeof AppIndexRoute
  '/app/appraisals/$teacherId': typeof AppAppraisalsTeacherIdRoute
  '/app/attendance/take': typeof AppAttendanceTakeRoute
  '/app/certificate/$progressId': typeof AppCertificateProgressIdRoute
  '/app/courses/$courseId': typeof AppCoursesCourseIdRoute
  '/app/invoice/$id': typeof AppInvoiceIdRoute
  '/app/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/app/srb/$studentId': typeof AppSrbStudentIdRoute
  '/app/training/$courseId': typeof AppTrainingCourseIdRoute
  '/app/appraisals': typeof AppAppraisalsIndexRoute
  '/app/attendance': typeof AppAttendanceIndexRoute
  '/app/courses': typeof AppCoursesIndexRoute
  '/app/srb': typeof AppSrbIndexRoute
  '/app/training': typeof AppTrainingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/ai-insights': typeof AppAiInsightsRoute
  '/app/appraisals': typeof AppAppraisalsRouteWithChildren
  '/app/assignments': typeof AppAssignmentsRoute
  '/app/attendance': typeof AppAttendanceRouteWithChildren
  '/app/awards': typeof AppAwardsRoute
  '/app/branding': typeof AppBrandingRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/children': typeof AppChildrenRoute
  '/app/coaching': typeof AppCoachingRoute
  '/app/compliance': typeof AppComplianceRoute
  '/app/courses': typeof AppCoursesRouteWithChildren
  '/app/finance': typeof AppFinanceRoute
  '/app/grades': typeof AppGradesRoute
  '/app/grading': typeof AppGradingRoute
  '/app/lms': typeof AppLmsRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/migration': typeof AppMigrationRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/squad': typeof AppSquadRoute
  '/app/srb': typeof AppSrbRouteWithChildren
  '/app/students': typeof AppStudentsRoute
  '/app/swim-reports': typeof AppSwimReportsRoute
  '/app/teacher-classes': typeof AppTeacherClassesRoute
  '/app/tenants': typeof AppTenantsRoute
  '/app/training': typeof AppTrainingRouteWithChildren
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
  '/app/appraisals/$teacherId': typeof AppAppraisalsTeacherIdRoute
  '/app/attendance/take': typeof AppAttendanceTakeRoute
  '/app/certificate/$progressId': typeof AppCertificateProgressIdRoute
  '/app/courses/$courseId': typeof AppCoursesCourseIdRoute
  '/app/invoice/$id': typeof AppInvoiceIdRoute
  '/app/sessions/$sessionId': typeof AppSessionsSessionIdRoute
  '/app/srb/$studentId': typeof AppSrbStudentIdRoute
  '/app/training/$courseId': typeof AppTrainingCourseIdRoute
  '/app/appraisals/': typeof AppAppraisalsIndexRoute
  '/app/attendance/': typeof AppAttendanceIndexRoute
  '/app/courses/': typeof AppCoursesIndexRoute
  '/app/srb/': typeof AppSrbIndexRoute
  '/app/training/': typeof AppTrainingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/ai-insights'
    | '/app/appraisals'
    | '/app/assignments'
    | '/app/attendance'
    | '/app/awards'
    | '/app/branding'
    | '/app/calendar'
    | '/app/children'
    | '/app/coaching'
    | '/app/compliance'
    | '/app/courses'
    | '/app/finance'
    | '/app/grades'
    | '/app/grading'
    | '/app/lms'
    | '/app/marketing'
    | '/app/marketplace'
    | '/app/messages'
    | '/app/migration'
    | '/app/onboarding'
    | '/app/profile'
    | '/app/reports'
    | '/app/settings'
    | '/app/squad'
    | '/app/srb'
    | '/app/students'
    | '/app/swim-reports'
    | '/app/teacher-classes'
    | '/app/tenants'
    | '/app/training'
    | '/app/users'
    | '/app/'
    | '/app/appraisals/$teacherId'
    | '/app/attendance/take'
    | '/app/certificate/$progressId'
    | '/app/courses/$courseId'
    | '/app/invoice/$id'
    | '/app/sessions/$sessionId'
    | '/app/srb/$studentId'
    | '/app/training/$courseId'
    | '/app/appraisals/'
    | '/app/attendance/'
    | '/app/courses/'
    | '/app/srb/'
    | '/app/training/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/ai-insights'
    | '/app/assignments'
    | '/app/awards'
    | '/app/branding'
    | '/app/calendar'
    | '/app/children'
    | '/app/coaching'
    | '/app/compliance'
    | '/app/finance'
    | '/app/grades'
    | '/app/grading'
    | '/app/lms'
    | '/app/marketing'
    | '/app/marketplace'
    | '/app/messages'
    | '/app/migration'
    | '/app/onboarding'
    | '/app/profile'
    | '/app/reports'
    | '/app/settings'
    | '/app/squad'
    | '/app/students'
    | '/app/swim-reports'
    | '/app/teacher-classes'
    | '/app/tenants'
    | '/app/users'
    | '/app'
    | '/app/appraisals/$teacherId'
    | '/app/attendance/take'
    | '/app/certificate/$progressId'
    | '/app/courses/$courseId'
    | '/app/invoice/$id'
    | '/app/sessions/$sessionId'
    | '/app/srb/$studentId'
    | '/app/training/$courseId'
    | '/app/appraisals'
    | '/app/attendance'
    | '/app/courses'
    | '/app/srb'
    | '/app/training'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/ai-insights'
    | '/app/appraisals'
    | '/app/assignments'
    | '/app/attendance'
    | '/app/awards'
    | '/app/branding'
    | '/app/calendar'
    | '/app/children'
    | '/app/coaching'
    | '/app/compliance'
    | '/app/courses'
    | '/app/finance'
    | '/app/grades'
    | '/app/grading'
    | '/app/lms'
    | '/app/marketing'
    | '/app/marketplace'
    | '/app/messages'
    | '/app/migration'
    | '/app/onboarding'
    | '/app/profile'
    | '/app/reports'
    | '/app/settings'
    | '/app/squad'
    | '/app/srb'
    | '/app/students'
    | '/app/swim-reports'
    | '/app/teacher-classes'
    | '/app/tenants'
    | '/app/training'
    | '/app/users'
    | '/app/'
    | '/app/appraisals/$teacherId'
    | '/app/attendance/take'
    | '/app/certificate/$progressId'
    | '/app/courses/$courseId'
    | '/app/invoice/$id'
    | '/app/sessions/$sessionId'
    | '/app/srb/$studentId'
    | '/app/training/$courseId'
    | '/app/appraisals/'
    | '/app/attendance/'
    | '/app/courses/'
    | '/app/srb/'
    | '/app/training/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/training': {
      id: '/app/training'
      path: '/training'
      fullPath: '/app/training'
      preLoaderRoute: typeof AppTrainingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tenants': {
      id: '/app/tenants'
      path: '/tenants'
      fullPath: '/app/tenants'
      preLoaderRoute: typeof AppTenantsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/teacher-classes': {
      id: '/app/teacher-classes'
      path: '/teacher-classes'
      fullPath: '/app/teacher-classes'
      preLoaderRoute: typeof AppTeacherClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/swim-reports': {
      id: '/app/swim-reports'
      path: '/swim-reports'
      fullPath: '/app/swim-reports'
      preLoaderRoute: typeof AppSwimReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/students': {
      id: '/app/students'
      path: '/students'
      fullPath: '/app/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/srb': {
      id: '/app/srb'
      path: '/srb'
      fullPath: '/app/srb'
      preLoaderRoute: typeof AppSrbRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/squad': {
      id: '/app/squad'
      path: '/squad'
      fullPath: '/app/squad'
      preLoaderRoute: typeof AppSquadRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/migration': {
      id: '/app/migration'
      path: '/migration'
      fullPath: '/app/migration'
      preLoaderRoute: typeof AppMigrationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marketplace': {
      id: '/app/marketplace'
      path: '/marketplace'
      fullPath: '/app/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marketing': {
      id: '/app/marketing'
      path: '/marketing'
      fullPath: '/app/marketing'
      preLoaderRoute: typeof AppMarketingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lms': {
      id: '/app/lms'
      path: '/lms'
      fullPath: '/app/lms'
      preLoaderRoute: typeof AppLmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/grading': {
      id: '/app/grading'
      path: '/grading'
      fullPath: '/app/grading'
      preLoaderRoute: typeof AppGradingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/grades': {
      id: '/app/grades'
      path: '/grades'
      fullPath: '/app/grades'
      preLoaderRoute: typeof AppGradesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/finance': {
      id: '/app/finance'
      path: '/finance'
      fullPath: '/app/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/courses': {
      id: '/app/courses'
      path: '/courses'
      fullPath: '/app/courses'
      preLoaderRoute: typeof AppCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/compliance': {
      id: '/app/compliance'
      path: '/compliance'
      fullPath: '/app/compliance'
      preLoaderRoute: typeof AppComplianceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coaching': {
      id: '/app/coaching'
      path: '/coaching'
      fullPath: '/app/coaching'
      preLoaderRoute: typeof AppCoachingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/children': {
      id: '/app/children'
      path: '/children'
      fullPath: '/app/children'
      preLoaderRoute: typeof AppChildrenRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/branding': {
      id: '/app/branding'
      path: '/branding'
      fullPath: '/app/branding'
      preLoaderRoute: typeof AppBrandingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/awards': {
      id: '/app/awards'
      path: '/awards'
      fullPath: '/app/awards'
      preLoaderRoute: typeof AppAwardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance': {
      id: '/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assignments': {
      id: '/app/assignments'
      path: '/assignments'
      fullPath: '/app/assignments'
      preLoaderRoute: typeof AppAssignmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/appraisals': {
      id: '/app/appraisals'
      path: '/appraisals'
      fullPath: '/app/appraisals'
      preLoaderRoute: typeof AppAppraisalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai-insights': {
      id: '/app/ai-insights'
      path: '/ai-insights'
      fullPath: '/app/ai-insights'
      preLoaderRoute: typeof AppAiInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/training/': {
      id: '/app/training/'
      path: '/'
      fullPath: '/app/training/'
      preLoaderRoute: typeof AppTrainingIndexRouteImport
      parentRoute: typeof AppTrainingRoute
    }
    '/app/srb/': {
      id: '/app/srb/'
      path: '/'
      fullPath: '/app/srb/'
      preLoaderRoute: typeof AppSrbIndexRouteImport
      parentRoute: typeof AppSrbRoute
    }
    '/app/courses/': {
      id: '/app/courses/'
      path: '/'
      fullPath: '/app/courses/'
      preLoaderRoute: typeof AppCoursesIndexRouteImport
      parentRoute: typeof AppCoursesRoute
    }
    '/app/attendance/': {
      id: '/app/attendance/'
      path: '/'
      fullPath: '/app/attendance/'
      preLoaderRoute: typeof AppAttendanceIndexRouteImport
      parentRoute: typeof AppAttendanceRoute
    }
    '/app/appraisals/': {
      id: '/app/appraisals/'
      path: '/'
      fullPath: '/app/appraisals/'
      preLoaderRoute: typeof AppAppraisalsIndexRouteImport
      parentRoute: typeof AppAppraisalsRoute
    }
    '/app/training/$courseId': {
      id: '/app/training/$courseId'
      path: '/$courseId'
      fullPath: '/app/training/$courseId'
      preLoaderRoute: typeof AppTrainingCourseIdRouteImport
      parentRoute: typeof AppTrainingRoute
    }
    '/app/srb/$studentId': {
      id: '/app/srb/$studentId'
      path: '/$studentId'
      fullPath: '/app/srb/$studentId'
      preLoaderRoute: typeof AppSrbStudentIdRouteImport
      parentRoute: typeof AppSrbRoute
    }
    '/app/sessions/$sessionId': {
      id: '/app/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/app/sessions/$sessionId'
      preLoaderRoute: typeof AppSessionsSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoice/$id': {
      id: '/app/invoice/$id'
      path: '/invoice/$id'
      fullPath: '/app/invoice/$id'
      preLoaderRoute: typeof AppInvoiceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/courses/$courseId': {
      id: '/app/courses/$courseId'
      path: '/$courseId'
      fullPath: '/app/courses/$courseId'
      preLoaderRoute: typeof AppCoursesCourseIdRouteImport
      parentRoute: typeof AppCoursesRoute
    }
    '/app/certificate/$progressId': {
      id: '/app/certificate/$progressId'
      path: '/certificate/$progressId'
      fullPath: '/app/certificate/$progressId'
      preLoaderRoute: typeof AppCertificateProgressIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance/take': {
      id: '/app/attendance/take'
      path: '/take'
      fullPath: '/app/attendance/take'
      preLoaderRoute: typeof AppAttendanceTakeRouteImport
      parentRoute: typeof AppAttendanceRoute
    }
    '/app/appraisals/$teacherId': {
      id: '/app/appraisals/$teacherId'
      path: '/$teacherId'
      fullPath: '/app/appraisals/$teacherId'
      preLoaderRoute: typeof AppAppraisalsTeacherIdRouteImport
      parentRoute: typeof AppAppraisalsRoute
    }
  }
}

interface AppAppraisalsRouteChildren {
  AppAppraisalsTeacherIdRoute: typeof AppAppraisalsTeacherIdRoute
  AppAppraisalsIndexRoute: typeof AppAppraisalsIndexRoute
}

const AppAppraisalsRouteChildren: AppAppraisalsRouteChildren = {
  AppAppraisalsTeacherIdRoute: AppAppraisalsTeacherIdRoute,
  AppAppraisalsIndexRoute: AppAppraisalsIndexRoute,
}

const AppAppraisalsRouteWithChildren = AppAppraisalsRoute._addFileChildren(
  AppAppraisalsRouteChildren,
)

interface AppAttendanceRouteChildren {
  AppAttendanceTakeRoute: typeof AppAttendanceTakeRoute
  AppAttendanceIndexRoute: typeof AppAttendanceIndexRoute
}

const AppAttendanceRouteChildren: AppAttendanceRouteChildren = {
  AppAttendanceTakeRoute: AppAttendanceTakeRoute,
  AppAttendanceIndexRoute: AppAttendanceIndexRoute,
}

const AppAttendanceRouteWithChildren = AppAttendanceRoute._addFileChildren(
  AppAttendanceRouteChildren,
)

interface AppCoursesRouteChildren {
  AppCoursesCourseIdRoute: typeof AppCoursesCourseIdRoute
  AppCoursesIndexRoute: typeof AppCoursesIndexRoute
}

const AppCoursesRouteChildren: AppCoursesRouteChildren = {
  AppCoursesCourseIdRoute: AppCoursesCourseIdRoute,
  AppCoursesIndexRoute: AppCoursesIndexRoute,
}

const AppCoursesRouteWithChildren = AppCoursesRoute._addFileChildren(
  AppCoursesRouteChildren,
)

interface AppSrbRouteChildren {
  AppSrbStudentIdRoute: typeof AppSrbStudentIdRoute
  AppSrbIndexRoute: typeof AppSrbIndexRoute
}

const AppSrbRouteChildren: AppSrbRouteChildren = {
  AppSrbStudentIdRoute: AppSrbStudentIdRoute,
  AppSrbIndexRoute: AppSrbIndexRoute,
}

const AppSrbRouteWithChildren =
  AppSrbRoute._addFileChildren(AppSrbRouteChildren)

interface AppTrainingRouteChildren {
  AppTrainingCourseIdRoute: typeof AppTrainingCourseIdRoute
  AppTrainingIndexRoute: typeof AppTrainingIndexRoute
}

const AppTrainingRouteChildren: AppTrainingRouteChildren = {
  AppTrainingCourseIdRoute: AppTrainingCourseIdRoute,
  AppTrainingIndexRoute: AppTrainingIndexRoute,
}

const AppTrainingRouteWithChildren = AppTrainingRoute._addFileChildren(
  AppTrainingRouteChildren,
)

interface AppRouteChildren {
  AppAiInsightsRoute: typeof AppAiInsightsRoute
  AppAppraisalsRoute: typeof AppAppraisalsRouteWithChildren
  AppAssignmentsRoute: typeof AppAssignmentsRoute
  AppAttendanceRoute: typeof AppAttendanceRouteWithChildren
  AppAwardsRoute: typeof AppAwardsRoute
  AppBrandingRoute: typeof AppBrandingRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppChildrenRoute: typeof AppChildrenRoute
  AppCoachingRoute: typeof AppCoachingRoute
  AppComplianceRoute: typeof AppComplianceRoute
  AppCoursesRoute: typeof AppCoursesRouteWithChildren
  AppFinanceRoute: typeof AppFinanceRoute
  AppGradesRoute: typeof AppGradesRoute
  AppGradingRoute: typeof AppGradingRoute
  AppLmsRoute: typeof AppLmsRoute
  AppMarketingRoute: typeof AppMarketingRoute
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppMigrationRoute: typeof AppMigrationRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSquadRoute: typeof AppSquadRoute
  AppSrbRoute: typeof AppSrbRouteWithChildren
  AppStudentsRoute: typeof AppStudentsRoute
  AppSwimReportsRoute: typeof AppSwimReportsRoute
  AppTeacherClassesRoute: typeof AppTeacherClassesRoute
  AppTenantsRoute: typeof AppTenantsRoute
  AppTrainingRoute: typeof AppTrainingRouteWithChildren
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCertificateProgressIdRoute: typeof AppCertificateProgressIdRoute
  AppInvoiceIdRoute: typeof AppInvoiceIdRoute
  AppSessionsSessionIdRoute: typeof AppSessionsSessionIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiInsightsRoute: AppAiInsightsRoute,
  AppAppraisalsRoute: AppAppraisalsRouteWithChildren,
  AppAssignmentsRoute: AppAssignmentsRoute,
  AppAttendanceRoute: AppAttendanceRouteWithChildren,
  AppAwardsRoute: AppAwardsRoute,
  AppBrandingRoute: AppBrandingRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppChildrenRoute: AppChildrenRoute,
  AppCoachingRoute: AppCoachingRoute,
  AppComplianceRoute: AppComplianceRoute,
  AppCoursesRoute: AppCoursesRouteWithChildren,
  AppFinanceRoute: AppFinanceRoute,
  AppGradesRoute: AppGradesRoute,
  AppGradingRoute: AppGradingRoute,
  AppLmsRoute: AppLmsRoute,
  AppMarketingRoute: AppMarketingRoute,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppMigrationRoute: AppMigrationRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSquadRoute: AppSquadRoute,
  AppSrbRoute: AppSrbRouteWithChildren,
  AppStudentsRoute: AppStudentsRoute,
  AppSwimReportsRoute: AppSwimReportsRoute,
  AppTeacherClassesRoute: AppTeacherClassesRoute,
  AppTenantsRoute: AppTenantsRoute,
  AppTrainingRoute: AppTrainingRouteWithChildren,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppCertificateProgressIdRoute: AppCertificateProgressIdRoute,
  AppInvoiceIdRoute: AppInvoiceIdRoute,
  AppSessionsSessionIdRoute: AppSessionsSessionIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
